### ISSUE TITLE
Error: cannot find module @date-io/core/IUtils

### ISSUE THREAD

**Issue by nzacca** [dmtrKovalenko/date-io#1]
Hello!

Nice refactor! I'm encountering the following error after updating.

```
ERROR in /<truncated>/node_modules/@date-io/moment/build/moment-utils.d.ts(2,24):
TS2307: Cannot find module '@date-io/core/IUtils'.
ERROR in /<truncated>/node_modules/material-ui-pickers/_shared/BasePicker.d.ts(1,24):
TS2307: Cannot find module '@date-io/core/IUtils'.
ERROR in /<truncated>/node_modules/material-ui-pickers/_shared/WithUtils.d.ts(1,24):
TS2307: Cannot find module '@date-io/core/IUtils'.
```

I was able to workaround the issue by manually installing the core package but I was wondering if perhaps it should be included as a dependency of the moment/date-fns/etc. packages instead?

This is where the problem is (which goes away after installing core):
https://github.com/dmtrKovalenko/date-io/blob/master/packages/moment/src/moment-utils.ts#L2

**Comment by dmtrKovalenko** [comment]
@nzacca you are using typescript?

**Comment by nzacca** [comment]
@dmtrKovalenko Yes.

**Comment by tjaskula** [comment]
I have the same problem with TS

**Comment by dmtrKovalenko** [comment]
Published in v0.0.2 with the fix

**Comment by ahce** [comment]
@dmtrKovalenko this issue came back in v1.2.0

**Comment by ee0pdt** [comment]
Can confirm, this is a live issue

`"@date-io/moment": "^1.3.5",`

**Comment by seanmccay** [comment]
I'm having this issue as well.

```
"typescript": "^3.3.4000"
"@date-io/moment": "^1.1.0"
"moment": "^2.22.2",
```

> node_modules/@date-io/moment/build/moment-utils.d.ts:2:24 - error TS2307: Cannot find module '@date-io/core/IUtils'.
> 
> 2 import { IUtils } from "@date-io/core/IUtils";
>                          ~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/material-ui-pickers/MuiPickersUtilsProvider.d.ts:1:24 - error TS2307: Cannot find module '@date-io/core/IUtils'.
> 
> 1 import { IUtils } from '@date-io/core/IUtils';
>                          ~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/material-ui-pickers/_shared/BasePicker.d.ts:3:24 - error TS2307: Cannot find module '@date-io/core/IUtils'.
> 
> 3 import { IUtils } from '@date-io/core/IUtils';
>                          ~~~~~~~~~~~~~~~~~~~~~~
> 
> node_modules/material-ui-pickers/_shared/WithUtils.d.ts:1:24 - error TS2307: Cannot find module '@date-io/core/IUtils'.
> 
> 1 import { IUtils } from '@date-io/core/IUtils';

**Comment by nzacca** [comment]
Issue was introduced here: https://github.com/dmtrKovalenko/date-io/commit/e0dfb67e6c0387c661642814db7a35c1bea3c709#diff-3c70df024fb0ca5df014877fa49bcc08L12

May be able to use a type import (ex. import("@date-io/core").IUtils) instead since it is only used to grab the `IUtils` type def.
