### ISSUE TITLE
why isn't date() using parseISO?

### ISSUE THREAD

**Issue by lifeiscontent** [dmtrKovalenko/date-io#107]
https://github.com/dmtrKovalenko/date-io/blob/5d337fc63dcdf70617b1c7e5d64964856071291c/packages/date-fns/src/date-fns-utils.ts#L128-L138

in another library https://material-ui-pickers.dev its causing ISO 8601 text strings to be formatted incorrectly.

https://codesandbox.io/s/blue-pond-1qll6

please advise.

**Comment by dmtrKovalenko** [comment]
We are just leveraging the recommended way by the date-fns team. They have removed the ability to create iso strings on the flight. So please do it manually like. `value={parseIso("2019-01-01")}`
