### ISSUE TITLE
@date-io/date-fns@0.0.2" has incorrect peer dependency "date-fns@2.0.0-alpha.21".

### ISSUE THREAD

**Issue by HriBB** [dmtrKovalenko/date-io#11]
I am using latest alpha `date-fns@2.0.0-alpha.25`.

**Comment by HriBB** [comment]
Probably just need to update [this](https://github.com/dmtrKovalenko/date-io/blob/master/packages/date-fns/package.json#L33) line.

**Comment by TrySound** [comment]
Next alpha introduced some breaking changes which we did not track. This package supports only alpha.21 for now.
