### ISSUE TITLE
Separate dev dependencies

### ISSUE THREAD

**Issue by deluksic** [dmtrKovalenko/date-io#134]
Looking at the dependency tree using this tool: 

http://npm.broofa.com/?q=@date-io/date-fns

Every project that uses this package (for example `material-table`) will pull all of these with it. Can you please factor out `lerna` at least, but others can be moved also.

Thank you!

**Comment by deluksic** [comment]
I can also make a PR if you like.

**Comment by TrySound** [comment]
Sure, I think this is done by accident.

**Comment by dmtrKovalenko** [comment]
https://github.com/dmtrKovalenko/date-io/blob/master/packages/date-fns/package.json

I am not sure 🤔

**Comment by deluksic** [comment]
Adding these links from PR for discussion here, both [npms.io](https://api.npms.io/v2/package/%40date-io%2Fdate-fns) and [npm.broofa.com](http://npm.broofa.com/?q=@date-io/date-fns) confirm `lerna` as dependency

**Comment by TrySound** [comment]
@dmtrKovalenko @deluksic Looks like this was fixed in master branch but not released yet.
https://github.com/dmtrKovalenko/date-io/commit/43167ee442d748268537f77ef4fbfa1ba22c334f

**Comment by deluksic** [comment]
I wasn't aware, thanks!

**Comment by dmtrKovalenko** [comment]
Released new version.
