### ISSUE TITLE
Date library peer dependencies

### ISSUE THREAD

**Issue by mvestergaard** [dmtrKovalenko/date-io#177]
Would it be possible to either relax the version constraint for date library peer dependencies, or publish more often?

The current version of `@date-io/date-fns` has a peer dependency for `date-fns@2.1.0` while the latest version is `2.4.1`.

It seems to be a pretty constant issue that this peer dependency isn't met when you strive to keep your dependencies up to date.

**Comment by TrySound** [comment]
@dmtrKovalenko I agree. Caret or >= would fit better.
