### ISSUE TITLE
Luxon does not support libInstance

### ISSUE THREAD

**Issue by spudcud** [dmtrKovalenko/date-io#179]
It looks like luxon utils does not support an instance being passed into the constructor like dayjs and moment. I am trying to force everything to be UTC and using libInstance on MuiPickersUtilsProvider is how it is done for dayjs and moment and it is not working for luxon.

I would use Dayjs except typing in the time does not work. Date-fns does not have UTC always support and now Luxon doesn't work either. I was trying not to use moment because it is a monolith but it looks like that is my only option.

**Comment by dmtrKovalenko** [comment]
I am really sorry for letting this issue floats, but is it really possible to somehow globally setup luxons `DateTIme` constructor?
