### ISSUE TITLE
Moment passing moment.utc into libInstance of MuiPickersUtilsProvider causes the calendar to fail.

### ISSUE THREAD

**Issue by spudcud** [dmtrKovalenko/date-io#180]
I am using `<MuiPickersUtilsProvider libInstance={moment.utc} utils={MomentUtils}>` to always display/use dates and times in UTC. Settings this causes the calendar to fail with `this.moment.weekdaysShort is not a function` error. This causes the ability to use UTC always to not be possible.

https://codesandbox.io/s/material-ui-pickers-usage-demo-g93c2

**Comment by guilleironhack** [comment]
I know this is a quite old issue, but I just happened to stumble upen this issue and I solved it by using `moment-timezone`:
```js
import moment from 'moment-timezone';
moment.tz.setDefault('Etc/UTC');

[...]

<MuiPickersUtilsProvider libInstance={moment} utils={MomentUtils}>
```

**Comment by sibelius** [comment]
should we have a `MomentUtilsUtc`?

**Comment by dmtrKovalenko** [comment]
I think more proper way is to override `date` function, that is basically take value and create a moment value. 
This is the best place to change time zone. Going to make some docs of how to inject timezone for pickers

**Comment by PSharon-7** [comment]
This might work for u.
https://codesandbox.io/s/keyboarddatetimepicker-moment-utc-demo-ukmyc

**Comment by dmtrKovalenko** [comment]
Closing cause moment is not the priority anymore
