### ISSUE TITLE
TypeScript definition issue with moment import - 

### ISSUE THREAD

**Issue by shadesofkae** [dmtrKovalenko/date-io#2]
When compiling with TypeScript, I receive the following error: 

```
Module '"/<truncated>/moment/moment"' has no default export
```

The moment import appears to be written as `import defaultMoment from "moment"`, but typically in TypeScript this is written as `import * as moment from "moment"`, since moment does not use an ES6 style default export.

**Comment by TrySound** [comment]
We encourage to enable `esModuleInterop` flag to solve this problem. The point is that `moment` import is callable and cannot be a namespace. Namespace is always an object with special type, not function. Rollup for example fails to bundle callable namespace which is widely and wrongly used by typescript.

**Comment by shadesofkae** [comment]
Thanks, the esModuleInterop flag is a valid solution (although bit of a pain to convert to on my large existing project).

**Comment by CharlieIGG** [comment]
Any other workaround that would not cause us to re-write stuff throughout all of our projects?

**Comment by dmtrKovalenko** [comment]
Use skilLibCheck

**Comment by yoonghan** [comment]
Could this import be modified as: 

> import * as defaultMoment from "moment";

in  ".node_modules/moment/moment"' has no default export. Which is based on https://momentjs.com/docs/#/use-it/typescript/

**Comment by dmtrKovalenko** [comment]
@yoonghan no, please follow the Readme `Typescript` section

**Comment by yoonghan** [comment]
I see, will stick on compilerOptions provided in Readme. It's working with that change, thank you so much.
