### ISSUE TITLE
Document usage from a library perspective

### ISSUE THREAD

**Issue by NateRadebaugh** [dmtrKovalenko/date-io#208]
It looks like this is a great way to avoid requiring a specific date lib as a dep/peer dep.

material-ui-pickers is implemented with something like:
```jsx
import MomentUtils from '@date-io/moment';
import DateFnsUtils from '@date-io/date-fns';
import LuxonUtils from '@date-io/luxon';
import { MuiPickersUtilsProvider } from '@material-ui/pickers';

function App() {
  return (
    <MuiPickersUtilsProvider utils={DateFnsUtils}>
      <Root />
    </MuiPickersUtilsProvider>
  );
}

render(<App />, document.querySelector('#app'));
```

Is there any way to auto-register the various utils to `global` to avoid requiring context? Or is this pattern with react context the best we can do?

# Issue

The best way for other libraries to work with this library should be documented.

**Comment by dmtrKovalenko** [comment]
Yeah, it is definitely something we need to have. I will work on this, but for now if you want to use it for some project I can describe how to use it and even help to integrate it

**Comment by NateRadebaugh** [comment]
I have a date/time picker library ([@nateradebaugh/react-datetime](https://bundlephobia.com/result?p=@nateradebaugh/react-datetime@4.2.0)) that used to have a peerDep on `date-fns` v1 but then v2 came out and I ended up bundling it into the lib as a dep, bloating the bundle size.
![image](https://user-images.githubusercontent.com/130445/68858947-d15e1680-06ab-11ea-9ff1-604370c3d47f.png)

I'd love to remove that dependency and just use whatever the consumer is using instead via some common interface, which is what it looks like what `date-io` does.

I'm not sure I love the ergonomics of requiring a context provider wrapper, but am interested in hearing what options there are.

Thanks!

**Comment by dmtrKovalenko** [comment]
Nothing over hard with using date-io. Overall it is only an adapter then wrapping instances, so everything you need is to receive from your user a proper utils class. The developer is importing @date-io/{lib} package and gives you (anyway, it may be direct prop or anything like context)

In muipickers we are just passing a function. And then doing

```
const utils = new props.Utils({ locale, ... })
```

And then inside your datepicker you will use only this utils to work with the date. Like to create a new object you will do `utils.date()` instead of `new Date()`. You will find the implemented interface in the readme and also in typescript definitions. 

So this way your users will be able to pass any sort of supported date/time libs object and receive back from you a `moment` or `luxon` or `Date` or any object.

**Comment by NateRadebaugh** [comment]
Is there a TypeScript interface I should be using as that "utils" prop?

**Comment by innocenzi** [comment]
> so everything you need is to receive from your user a proper utils class

I thought it was a library that a vendor could use to use the same date library than a user in their project. i.e. a user has a project which uses Luxon, and the vendor offers a calendar component which should be data library-agnostic. 

Am I wrong there? The user *has* to install `data-io` too?

**Comment by dmtrKovalenko** [comment]
Yes, and this is the main reason for this lib. User install any lib he wants and you as library consumer can work with it

**Comment by innocenzi** [comment]
Alright, thanks. Did you explore ways for users to not have to depend on `date-io`? It's okay to do so, but it would be best if the user would be able to not care at all. 

Something like a resolver in `date-io` which would return the correct interfaced date utils, depending on the result of a dependency check? This way, only the vendor would have to depend on `date-io`. I don't even know if this is possible? I know Webpack has `resolve` and `resolveWeak`, Node has `require.resolve`, and not sure how to do it with Rollup, nor how to handle both Node and browsers. 

---

Here is what I mean:

```ts
// date-io

function resolve(): IUtils<Date> {
 // do the dependency checks here and return the correct adapter
}

export const date = resolve(); // or whatever, you got the idea
```

```js
// vendor code, uses date-io
import { date } from 'date-io`;

date.isValid(someOtherDateVariable);
```

```js
// user code, doesn't care about date-io
import { DateTime } from 'luxon';
DateTime.local();
```
