### ISSUE TITLE
Curried functions

### ISSUE THREAD

**Issue by dmtrKovalenko** [dmtrKovalenko/date-io#22]
Migrate to the curried functions to make it easier use of [pipeline operator](https://github.com/tc39/proposal-pipeline-operator).

**Comment by micha149** [comment]
The wording "carried function” is pretty new to me. Does it mean to create function which will work outside of the class context to be able to use destructuring?

**Comment by dmtrKovalenko** [comment]
https://www.sitepoint.com/currying-in-functional-javascript/

**Comment by micha149** [comment]
ok… currying is familar to me. Maybe you should fix the typos in title and description?!

**Comment by dmtrKovalenko** [comment]
That sound like complete nonsense to me after 4 years
