### ISSUE TITLE
moment-timezone

### ISSUE THREAD

**Issue by bartmelton** [dmtrKovalenko/date-io#234]
Is there a way to incorporate moment-timezone with this?  Particularly being able to set the default timezone?

**Comment by dmtrKovalenko** [comment]
You can pass moment-time zone right to the `libInstance` in this case it will use time zone set of the moment instance or global one

**Comment by scottlamb** [comment]
Can I trouble you for an example of constructing an instance this is happy with? I'd prefer that to messing with global defaults.

I've [tried various garbage](https://stackoverflow.com/questions/66697563/material-ui-localizationprovider-for-a-remote-time-zone) but nothing quite right so far.

**Comment by daniellizik** [comment]
@scottlamb "lib instance" in this case means the `instance` property in the object you send to the adapter constructor

```
import MomentAdapter from '@material-ui/pickers/adapter/moment';
import momentTz from 'moment-timezone';

const { moment: momentTimezone } = new MomentAdapter({ moment: momentTz })
```
