### ISSUE TITLE
2.x suggests @material-ui/pickers v4 but I don't see that anywhere?

### ISSUE THREAD

**Issue by aprilmintacpineda** [dmtrKovalenko/date-io#249]
https://github.com/dmtrKovalenko/date-io/releases/tag/v2.0.0

![image](https://user-images.githubusercontent.com/21032419/71977426-bcd56f00-3253-11ea-8590-66cab0a5ad04.png)

But I don't see v4 in the releases https://github.com/mui-org/material-ui-pickers/releases

**Comment by dmtrKovalenko** [comment]
Yeah, there is no v4 yet

**Comment by p45mark** [comment]
Any more info on this? I'm wondering if that should read "material-ui/core v4?" 

Any issues with upgrading if we're using `@material-ui/pickers` v3.2.8?

**Comment by dmtrKovalenko** [comment]
yes it means excatly that you **must not update if you using @material-ui/pickers v3.x**

**Comment by aprilmintacpineda** [comment]
Hmmm... isn't that quite odd that there's already a release that depends on a dependency that isn't out yet?

**Comment by dmtrKovalenko** [comment]
This package is not depends on material-ui-pickers. Pickers depends on date-io

**Comment by aprilmintacpineda** [comment]
Ah, I understand now. So 2.x has a breaking change that's not compatible with material-ui-pickers 3.x so material-ui-pickers has to catch up. Sorry I got confused.
