### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by hrafaelveloso** [dmtrKovalenko/date-io#251]
The new version, 2.0.0, in the releases tab has this warning:

### Do not update if you are not using @material-ui/pickers v4

Currently in npm the @material-ui/pickers, the version is 3.2.8. 

Where do I find that v4?

**Comment by mozbhearsum** [comment]
I am also confused about this.

**Comment by dmtrKovalenko** [comment]
Changed to 
## **Do not update if you are using @material-ui/pickers v3**
