### ISSUE TITLE
v2 stops working with {MuiPickersUtilsProvider} from "@material-ui/pickers"

### ISSUE THREAD

**Issue by zevero** [dmtrKovalenko/date-io#258]
v1.3.13 still works

**Comment by dmtrKovalenko** [comment]
Read the release notes

**Comment by mbifulco** [comment]
@dmtrKovalenko is there going to be an item in the release notes when we _can_ start using `@latest` with  `@material-ui/pickers`?

**Comment by Forfold** [comment]
@dmtrKovalenko I'm also curious of this. We are using both `luxon` and `@material-ui/pickers` in our project and don't really have an option to remove one or the other at this time.
