### ISSUE TITLE
Will this library be usable with material-ui-pickers in the future?

### ISSUE THREAD

**Issue by mbifulco** [dmtrKovalenko/date-io#289]
Carrying over my comment from https://github.com/dmtrKovalenko/date-io/issues/258 (which is closed)

> @dmtrKovalenko is there going to be an item in the release notes when we can start using @latest with @material-ui/pickers?

Per the release notes,  [v2.0.0](https://github.com/dmtrKovalenko/date-io/releases/tag/v2.0.0) is not compatible with the `@material-ui/pickers` library.  Is there a plan to remunerate that, or something I can do to help?

**Comment by dmtrKovalenko** [comment]
It is already using in v4 alpha versions

**Comment by Forfold** [comment]
@dmtrKovalenko Any update?

**Comment by dmtrKovalenko** [comment]
It is, but for version of material-ui-pickers 4+ or materila-ui v5
