### ISSUE TITLE
How to localize dayjs?

### ISSUE THREAD

**Issue by dominikbulaj** [dmtrKovalenko/date-io#29]
Hi,

I want to localize dayjs as it's lib I use in project. I tried:
`<MuiPickersUtilsProvider utils={DayJsUtils} locale={'de'}>`
but no lack.

I tried also (similar to `moment` example):
```
import { MuiPickersUtilsProvider } from 'material-ui-pickers'
import dayjs from 'dayjs'
import 'dayjs/locale/de'
import DayJsUtils from '@date-io/dayjs'

dayjs.locale('de')
```
in this case date picker is still not localized (week days, month names).

Any hint how should I do it?

Thanks in advice!

**Comment by dmtrKovalenko** [comment]
@dominikbulaj thanks a lot for sharing this issue. That is `date-io` bug and that's my fault it just doesn't implemented. I will fix that ASAP

**Comment by StudioSpindle** [comment]
How can dayjs be used then? Trying the same as https://github.com/dmtrKovalenko/date-io/issues/29#issuecomment-462314059 but no luck?
