### ISSUE TITLE
CHANGELOG.md is needed

### ISSUE THREAD

**Issue by drac** [dmtrKovalenko/date-io#30]
It would be so much better if we had a **CHANGELOG.md** to make it easier for users and contributors to see precisely what notable changes have been made between each release.

**Comment by dmtrKovalenko** [comment]
@drac I am not the fan of CHANGLOG.md file. All changes are placed in https://github.com/dmtrKovalenko/date-io/releases

**Comment by drac** [comment]
@dmtrKovalenko actually this works for me, and my mistake that I didn't check releases to see the changes. Sorry.
