### ISSUE TITLE
Can't resolve 'date-fns/addDays' 

### ISSUE THREAD

**Issue by Rick83600** [dmtrKovalenko/date-io#33]
Module not found: Can't resolve 'date-fns/addDays' in '/home/tristan/Documents/github/ui/node_modules/@date-io/date-fns/build'

"@date-io/moment": "^1.1.0"

work well with yarn, not with npm

**Comment by dmtrKovalenko** [comment]
Please provide more information.

**Comment by GarethBeddis** [comment]
I'm also having this issue. What information are you looking for? I've installed [Material Table](https://www.npmjs.com/package/material-table) which requires date-fns. My entire error log is below:

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/addDays' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 1:0-39 45:15-22 185:22-29
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/addMonths' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 2:0-43 150:15-24 153:15-24
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/addYears' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 3:0-41 197:22-30
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/differenceInMilliseconds' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 4:0-73 51:15-39
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/eachDayOfInterval' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 5:0-59 170:15-32
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/endOfDay' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 6:0-41 63:15-23 123:29-37
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/endOfMonth' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 26:0-45 87:15-25 177:28-38
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/endOfWeek' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 7:0-43 172:17-26 177:18-27
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/endOfYear' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 8:0-43 132:29-38 192:22-31
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/getHours' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 10:0-41 66:15-23
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/getSeconds' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 11:0-45 75:15-25
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/getYear' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 12:0-39 90:15-22
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/isAfter' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 13:0-39 54:15-22 123:15-22 132:15-22
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/isBefore' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 14:0-41 57:15-23 126:15-23 129:15-23 181:15-23 195:15-23
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/isEqual' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 15:0-39 117:15-22
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/isSameDay' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 16:0-43 81:15-24
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/isValid' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 17:0-39 48:15-22
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/setHours' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 19:0-41 69:15-23
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/setMinutes' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 20:0-45 72:15-25
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/setMonth' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 21:0-41 144:15-23
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/setSeconds' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 22:0-45 78:15-25
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/setYear' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 23:0-39 93:15-22
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/startOfDay' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 24:0-45 60:15-25 126:30-40
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/startOfMonth' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 25:0-49 84:15-27 176:32-44
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/startOfWeek' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 27:0-47 171:19-30 176:20-31
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

ERROR in ./node_modules/@date-io/date-fns/build/index.esm.js
Module not found: Error: Can't resolve 'date-fns/startOfYear' in 'D:\project_folder\node_modules\@date-io\date-fns\build'
 @ ./node_modules/@date-io/date-fns/build/index.esm.js 28:0-47 129:30-41 156:25-36 191:24-35
 @ ./node_modules/material-table/dist/m-table-filter-row.js
 @ ./node_modules/material-table/dist/material-table.js
 @ ./client/app/pages/details-page.js
 @ ./client/app/app.js
 @ ./client/app/index.js

**Comment by MATA0406** [comment]
I've solved the same problem as you!
https://material-ui-pickers.dev/getting-started/usage
Get on here. Open the CodeSandbox shown on the screen.
Please refer to package.json to make the same version of deviance.
I don't know exactly what the problem is, but I think it's the version of date-fns.

**Comment by minaibrahimsaid** [comment]
@MATA0406 
you saved my day

**Comment by yejiyang** [comment]
I got the same issue as @GarethBeddis described when I installed the [material table](https://material-ui.com/components/tables/#material-table). 

[This](https://github.com/mui-org/material-ui-pickers/issues/240) solution helped me. 
```
$ npm i --save date-fns@next @date-io/date-fns
```

**Comment by eddkalosha** [comment]
add

npm i @date-io/date-fns date-fns@next

**Comment by cif** [comment]
Any thoughts on publishing the latest version of this library? Anyone starting a new Material UI project is going to run into this issue.  I realize it's just as much the Material UI folks jumping the gun, and I hate to make work more work for folks working hard on OS projects but... please?

**Comment by RobertoMessaBrasil** [comment]
you have to install @types/date-fns also

**Comment by valihealthcare** [comment]
I tried all three of the above, the error has gone, so I guess something worked

**Comment by sgnl** [comment]
installing `@types/date-fns` was the only step I took to resolve my issue

**Comment by jhjdev** [comment]
> installing `@types/date-fns` was the only step I took to resolve my issue

Thank you @sgnl I had this issue on a project I was setting up for a client, and this solved the issue. Running a React Typescript project.

**Comment by jannnik** [comment]
`yarn cache clean', 'rm -rf node_modules', `yarn install` fixed it for me.
