### ISSUE TITLE
native

### ISSUE THREAD

**Issue by mfulton26** [dmtrKovalenko/date-io#339]
Is there a binding for JavaScript's built-in date implementation? I know it isn't perfect but that could be ideal for some use cases (e.g. I want to use `@material-ui/pickers` and I'm currently getting all of my dates from the server as ISO8601 strings so I'm not actually using `moment` or anything but `@material-ui/pickers` uses `date-io` but I don't see a native binding)

**Comment by dmtrKovalenko** [comment]
No, but there is a date-fns binding which itself is just a set of functions over native Date. You can use it, or if you worry about bundlesize you can take days, which is only 4kb gzip.

🧐 The main reason is that if we will implement all logic by ourselves we will have around the same size as with library. So just choose an appropriate library for your app and use it. 🤓


Best regards,
Dmitriy Kovalenko
14 апр. 2020 г., в 23:30, Mark Fulton <notifications@github.com> написал(а):

﻿

Is there a binding for JavaScript's built-in date implementation? I know it isn't perfect but that could be ideal for some use cases (e.g. I want to use @material-ui/pickers and I'm currently getting all of my dates from the server as ISO8601 strings so I'm not actually using moment or anything but @material-ui/pickers uses date-io but I don't see a native binding)

**Comment by mfulton26** [comment]
okay nice, that makes more sense now; thank you!

**Comment by Phoenixmatrix** [comment]
I was going to open the same issue until I found this one. Looking at the adapter code for the existing libs, and thinking of how they'd be implemented over native Date/Intl API, I'm not sure there's a whole lot to reimplement. The code to map from Dayjs or Moment to date-io is fairly similar to what one would do to map from the native objects in all but a few exceptions.

More importantly, it's really for dependency management. Having to deal with extra dependencies, possibly conflicting ones, is just a pain if you don't need to, so I think there's value in a native date adapter.

If nothing else, it would make for a great reference implementation to better understand what the adapters are trying to do.

**Comment by onlywei** [comment]
I would love to have a native adapter to avoid having to install either `date-fns` or `dayjs` in my package and then install it again in my app and then in my other package of a monorepo. Then I have to worry about the version of all of these things being the same...
