### ISSUE TITLE
startOfWeek and endOfWeek for date-fns not aware of locale

### ISSUE THREAD

**Issue by cbranch101** [dmtrKovalenko/date-io#342]
Would it possible to pass the locale to `startOfWeek` and `endOfWeek` in `date-fns-utils` similar to the way it's being passed to `format`?

**Comment by dmtrKovalenko** [comment]
Yeah, It is a bug. Need to simply pass second argument { locale: this.locale } here https://github.com/dmtrKovalenko/date-io/blob/master/packages/date-fns/src/date-fns-utils.ts#L189

Would you like to open a PR?

**Comment by cbranch101** [comment]
Yep, I'll do that right now

**Comment by cbranch101** [comment]
Actually, now that I think about it a little bit more, doesn't this need to be applied to every implementation, not just `date-fns`

For example for `moment`
```
  public startOfWeek(date: Moment) {
    return date.clone().startOf("week");
  }
```

Wouldn't I need to add `date.locale(this.locale);` similar to what's in `formatByString`

**Comment by dmtrKovalenko** [comment]
Local locale assignment is done on the `utils.date` step. So we just don’t need to worry about locale.

**Comment by dmtrKovalenko** [comment]
Releases in 2.6.1
