### ISSUE TITLE
Strategy for reliably changing the locale of a utils class

### ISSUE THREAD

**Issue by cbranch101** [dmtrKovalenko/date-io#347]
I've been working on a series of [PRs](https://github.com/uber/baseweb/pull/2968) to use `date-io` inside of [`baseweb`](https://baseweb.design/)

For the most part, the transition has been pretty smooth, but I hit a blocker with the way that locales are handled.  

As of now, there doesn't seem to be a mechanism for changing the locale in a`date-io` utils instance. You can pass a locale into the constructor, but that just wont' work in `baseweb`. For example, here's one of the helpers I'm to re-implement. 

```javascript
export function getStartOfWeek(date: Date, locale: any, adapter) {
  // how do we take locale into account? 
  return adapter.startOfWeek(date);
}
```

`adapter` is the `date-io` utils instance, and it only gets created once.  How exactly are we supposed to get that locale value applied to this instance? 

I tried a few things, first I thought about setting and resetting the this.locale on the adapter object

```javascript
export function getStartOfWeek(date: Date, locale: any, adapter) {
  previousLocale = adapter.locale;
  adapter.locale = locale;
  const returnValue = adapter.startOfWeek(date);
  adapter.locale = previousLocale;
  return returnValue
}
```

But after looking through all of the different date-io utils classes there are a couple(this one [for example](https://github.com/dmtrKovalenko/date-io/blob/master/packages/dayjs/src/dayjs-utils.ts#L65-L71)) that do processing in their constructor that wouldn't be correctly repeated when changing this.locale

```javascript
  const getAdapterWithNewLocale = (adapter, locale) => {
    const className = this.adapter.constructor.name;
    const UtilsClass = this.adapter.constructor;
    const options = getOptions(this.adapter) // how do we get the options?;
    return new UtilsClass({...options, locale});
  };

export function getStartOfWeek(date: Date, locale: any, adapter) {
  return getAdapterWithNewLocale(adapter, locale).startOfWeek(date);
}
```

The other option I could think of was to create a new utils instance with the provided locale.  While this solves the problem of reliably running the constructor and ensuring that all of the different utils classes will behave right, it creates a new problem of needing to be able to get the initial options that were passed in to recreate the instance.  

Because our strategy relies providing the instance as a react prop by the time we get the instance, we don't know which options were passed into it.  While we could change our implementation to pass the options instead of the instance, that would be much less intuitive, and would require creating the instance inside of the component. 

There are two solutions I can think of, both of which would unfortunately require changes to every Utils class. 

First, set the options passed into the utils class on a public property in every constructor, that way we can get them back out and recreate the instance.  Second, and probably the preferred option for me, would be to create a new public method on every utils class that is `changeLocale` that would ensure that everything required to actually change the locale was called. 

Do either of these sound viable?  Also, if I've missed something and you have a simpler solution, I'm totally open to it.

**Comment by dmtrKovalenko** [comment]
First of all, I am happy to hear about the new user of date-io 🎉 . Let me know if anything needs :) 

My initial thought was to make a utils class be primarily dependent on the locale. So we basically need to create a new instance on each locale change. 

```js
const utils = new Utils({ locale })
```

And rerender components by passing a new prop (each new object created will rerender a component and update react hooks). I am not sure about this line, could you explain it more? 
>  it creates a new problem of needing to be able to get the initial options that were passed in to recreate the instance.

**Comment by cbranch101** [comment]
Thanks for the heads up the component tree considerations, luckliy, all of that should work because an update to the component tree is what was kicking off the original function call, so components are updating correctly, we just need the helpers functions to return the right values when they're called with a different locale. 

As far your second question, I think a better example will probably help

```javascript
const instance = new DateFnsUtils({locale: en, formats});
const startOfWeek = (date, locale) => {
    // if we do it this way, it doesn't include the formats passed into 
    // the original instance, which it needs to
    const instanceForNewLocale = new DateFnsUtils({ locale })
    return instanceForNewLocale.startOfWeek(date);
}
```

**Comment by dmtrKovalenko** [comment]
I think in this case you just don’t need to think about it at all. Once object users created any user can do the following `const utils = React.useMemo(new Utils({ locale }))`. 

But if you accept a locale as a prop probably you need to make a breaking change and remove this prop. Because it is useless in case of interop (only if you don’t create adapter manually by passed props, just like in material-ui-pickers). 

Also you can close utils object. 

```js
let clone = Object.assign( Object.create( Object.getPrototypeOf(orig)), utils);
clone.locale = newLocale
```

**Comment by cbranch101** [comment]
So, I would actually love to do what you're describing, but the only way I'm going to be able to add the date library swapping functionality to `baseweb` right now is if its requires no changes to the existing apps. 

I'm sure you can imagine that requiring every front-end app that Uber has deployed in production to uptake a change is probably not going to happen, or if it is, it's not going to be for quite some time. Keep in mind, I don't work for Uber, I'm just trying to get this PR through for a use case for my own company. 

If there's just no way to do that, I totally understand, but then that means I just need to stop moving forward on this PR. 

The example I posted above was actually an attempt at using cloning, let me try to explain better what I was getting at.  In the example below, I'm able to clone an instance and pass in a new locale, the problem is that if the user passed anything other than locale into the constructor, that data will be lost when the instance is cloned. 

```javascript
const instance = new DateFnsUtils({
  formats: {
    year: 'y',
  },
});

console.log(instance.formats.year); // y, updated value
console.log(instance.locale); // undefined

const cloneUtilsInstanceWithNewLocale = (utilsInstance, locale) => {
  const UtilsClass = utilsInstance.constructor;
  return new UtilsClass({locale});
};

const clonedInstance = cloneUtilsInstanceWithNewLocale(instance, 'newLocale');

console.log(clonedInstance.locale); // newLocale
console.log(clonedInstance.formats.year); // YYYY default value, because it isn't set
```

What would fix this for us, is if the options that the user passed in were stored somewhere, so that we could recreate the instance and all would be good. 


```javascript
...
const cloneUtilsInstanceWithNewLocale = (utilsInstance, locale) => {
  const UtilsClass = utilsInstance.constructor;
 // new options property that's set in all constructors
  return new UtilsClass({ ...utilsInstance.options, locale });
};

const clonedInstance = cloneUtilsInstanceWithNewLocale(instance, 'newLocale');

console.log(clonedInstance.locale); // newLocale
console.log(clonedInstance.formats.year); // y, updated value, everything works!
```

Thanks for your help in trying to move this thing forward, hopefully we can find something that fits this specific use case.

**Comment by dmtrKovalenko** [comment]
```js
const cloneUtilsInstanceWithNewLocale = (utilsInstance, locale) => {
  let utilsClone = Object.assign( Object.create( Object.getPrototypeOf(orig)), utilsInstance);
  utilsClone.locale = locale

  return utilsClone
};
```

This should works as extended with saving every prop in protope and class object. But this is a weird workaround that ideally should require a breaking change for user
