### ISSUE TITLE
Property 'getStartOfMonth' is missing in type 'MomentUtils' but required in type 'IUtils<Moment>

### ISSUE THREAD

**Issue by cescoferraro** [dmtrKovalenko/date-io#35]
I am getting the following error with typescript

> ERROR in /home/cescoferraro/go/src/github.com/onnidev/dash/node_modules/@date-io/moment/build/moment-utils.d.ts(8,22):
> TS2420: Class 'MomentUtils' incorrectly implements interface 'IUtils<Moment>'.
>   Property 'getStartOfMonth' is missing in type 'MomentUtils' but required in type 'IUtils<Moment>'

**Comment by dmtrKovalenko** [comment]
Yep. You need to update pickers to use new version of date fns

**Comment by cescoferraro** [comment]
I did 

`npm i @date-io/date-fns date-fns@next
`
changed the provider to

`
    <MuiPickersUtilsProvider utils={DateFnsUtils}>
`

and got 
> Uncaught RangeError: `options.awareOfUnicodeTokens` must be set to `true` to use `DD` token; see: https://git.io/fxCyr

Do you know how can I silent the error so I can stop breaking CI?
Things are running perfect with Moment. Not that I want Moment in my bundle, but it seems to be the only one that played well for me.

**Comment by dmtrKovalenko** [comment]
@cescoferraro stop using `YYYY`, use `yyyy` and use `dd` instead of `DD`

**Comment by cescoferraro** [comment]
@dmtrKovalenko I thought it was an internal thing.
Replaced all occurrences here and it worked!
