### ISSUE TITLE
Support for strict mode parsing

### ISSUE THREAD

**Issue by jojkos** [dmtrKovalenko/date-io#364]
**Suppot for strict mode parsing is missing**
```javascript
import DayJsAdapter from "@date-io/dayjs";

const dayjs = new DayJsAdapter ();
const date = dayjs.parse("99.99.9999", "DD.MM.YYYY"); // is parsed as 07.06.10007
date.toString(); // "Wed, 06 Jun 10007 22:00:00 GMT"
```

**expected behavior**
```javascript
const date = dayjs.parse("99.99.9999", "DD.MM.YYYY", true); // third parameter is for strict mode
date.isValid(); // false
```
examples in documentations of the date libraries

-  dayJs https://day.js.org/docs/en/parse/string-format#__docusaurus
- moment.js https://momentjs.com/guides/#/parsing/strict-mode/

**Comment by dmtrKovalenko** [comment]
Regarding #407 this issue not reproducing. Added your case as pinning test
