### ISSUE TITLE
Cannot find module "@date-io/type"

### ISSUE THREAD

**Issue by harishvalluru05** [dmtrKovalenko/date-io#372]
1. We used @material-ui/pickers in one project and created distribution(dist) folder/created a package for the project.

2. when we try to use this package version in another project it is throwing an error **Cannot find module "@date-io/type"**.

Actually we are facing this issue when we are handling with distribution(dist) folder, But in the same project it is working fine.

Observation: 
   We identified that "@date-io/type" is a ambient module which is forcing us to include in 
   distribution folder which is not correct.

Please suggest

**Comment by dmtrKovalenko** [comment]
You can create your own declaration using `declare module`

**Comment by dmtrKovalenko** [comment]
We are removing `@date-io/type` at all
