### ISSUE TITLE
Module not found: Can't resolve 'date-fns/addDays' in 'C:\projects\...\node_modules\@date-io\date-fns\build'

### ISSUE THREAD

**Issue by dy** [dmtrKovalenko/date-io#38]
After including `npm i @date-io/date-fns`

**Comment by dmtrKovalenko** [comment]
You must install date-fns@next

**Comment by vinagrito** [comment]
@dmtrKovalenko maybe it is a good idea to include this somewhere in the readme or why not making it a dependency?.

**Comment by eps1lon** [comment]
@vinagrito You should get a warning like 
> warning " > @date-io/date-fns@1.3.5" has incorrect peer dependency "date-fns@2.0.0-alpha.27".

Had the issue myself but in the end I should've payed closer attention to my console.

**Comment by vinagrito** [comment]
@eps1lon I'm sure you're correct. I can't say I paid 100% attention to the log 😅. Thx!
