### ISSUE TITLE
Add formatters: fullDateWithWeekday, weekday and weekdayShort

### ISSUE THREAD

**Issue by philipbulley** [dmtrKovalenko/date-io#399]
I'd like to request a few additional formats to be added as follows:

```js
/** Localized full date with weekday, useful for accessibility @example "Tuesday, January 1st, 2019" */
fullDateWithWeekday: TLibFormatToken;

/** Weekday format string @example "Wednesday" */
weekday: TLibFormatToken;

/** Short weekday format string @example "Wed" */
weekdayShort: TLibFormatToken;
```

### Why?
I'm creating a Date Picker (for React Native) and feel its important for accessibility that the weekday, month, day, and year can be read out aloud by a screen reader.

### Why not just pass a custom format string?
I don't want end-users of the date picker to have to pass in a custom formatter string to achieve this, simply because accessibility is often ignored and this issue will rarely be visible to developers. We really need to ship with a good default.

### Why aren't the existing `defaultFormats` suitable?
* `fullDate` outputs `January 1st, 2019` and doesn't contain the weekday
* `normalDateWithWeekday` outputs `Wed, Jan 1st` and as such is not suitable for screen readers due to the abbreviations of weekday and month
* There are no `defaultFormats` that can output the weekday alone which would otherwise allow a suitable string to be built through multiple `format()` calls

@dmtrKovalenko, if you're fine with this addition, I'd be happy to submit a PR.

**Comment by dmtrKovalenko** [comment]
@philipbulley thanks for this issue! we definitely need it. 

It will be really cool if you will open PR with functionality. Thanks ❤️

**Comment by philipbulley** [comment]
@dmtrKovalenko  I've also just noticed that the existing `fullDate` doesn't work as per the docs.

Given these docs:
```js
/** Localized full date, useful for accessibility @example "January 1st, 2019" */
fullDate: TLibFormatToken;
```

The tests have assertions that don't match the example in the docs:
https://github.com/dmtrKovalenko/date-io/blob/e8ce35c2c6576e8118dd35950420770074568081/__tests__/formats.test.ts#L40

Making `fullDate` unsuitable for accessibility and screen readers as month abbreviations are used.

If you're not keen on making a breaking change here, would it be a good idea to introduce formatters named `a11yFullDate` and change the proposed `fullDateWithWeekday` to `a11yFullDateWithWeekday`? I'm happy to make the changes as part of #400, just let me know what you'd prefer.

**Comment by dmtrKovalenko** [comment]
There is `keyboardDate` that is suitable for keyboard input. But agree that it should be more default behavior

**Comment by philipbulley** [comment]
https://github.com/dmtrKovalenko/date-io/blob/e8ce35c2c6576e8118dd35950420770074568081/packages/core/IUtils.d.ts#L42-L43

Yeah, I'm thinking more about text-to-speech, as such `Tuesday, January 1st, 2019` would be more suitable than `2019/01/01`.

**Comment by dmtrKovalenko** [comment]
Already released
