### ISSUE TITLE
"prettier" missing from @date-io/core package.json

### ISSUE THREAD

**Issue by Hybrid-Force** [dmtrKovalenko/date-io#417]
`prettier` required here:
https://github.com/dmtrKovalenko/date-io/blob/25036d2ad2155f77e48edcb662c877431102f9fd/packages/core/IUtils.d.ts#L1

But the dependency is missing from `package.json` of the core package.

**Comment by dmtrKovalenko** [comment]
It's a bug. And was imported accidentally
