### ISSUE TITLE
There are no published core packages above 1.2.0 on NPM

### ISSUE THREAD

**Issue by artemnesterenko** [dmtrKovalenko/date-io#43]
There are no published core packages above 1.2.0 on NPM

**Comment by wmturmina** [comment]
Waiting for this to start use the new @material-ui/pickers
`@material-ui/pickers@3.0.0-rc.0 requires a peer of @date-io/core@^1.3.0 but none is installed. You must install peer dependencies yourself`

**Comment by artemnesterenko** [comment]
@wmturmina came here because of the same issue. In the 3.0.0 version of material pickers, this has been fixed https://github.com/mui-org/material-ui-pickers/issues/1057
