### ISSUE TITLE
Can I use the latest date-io release with material-pickers v3?

### ISSUE THREAD

**Issue by ldiqual** [dmtrKovalenko/date-io#453]
I'm using @material-ui/pickers 3.2.10. [date-io v2](https://github.com/dmtrKovalenko/date-io/releases/tag/v2.0.0) says that it's not safe to upgrade to v2 while using pickers v3. Is that still the case?

**Comment by dmtrKovalenko** [comment]
No

**Comment by djmitche** [comment]
There are two different questions in this issue, and I'm not sure which one you answered.

Is @date-io/date-fns@2.10.6 safe to use with @material-ui/pickers v3?

If not, what is the issue we can watch to know when it is safe?
