### ISSUE TITLE
getMeridiemText() always returns AM/PM format regardless of moment locale

### ISSUE THREAD

**Issue by ScripterSugar** [dmtrKovalenko/date-io#473]
[Related to this issue](https://github.com/mui-org/material-ui-pickers/issues/2124)

getMeridiemText() from moment utils always returns AM/PM as untranslated format, even moment locale has set to other languages.

It should returns translated AM/PM text, not only in English format.

**Comment by dmtrKovalenko** [comment]
Yes it is hard coded for now. Do you have any idea how to extract the text directly from moment locale?

**Comment by ScripterSugar** [comment]
I solved my problem by creating override function for this method but didn't had time to create a PR for the modification.

In my implementation I used moment().localeData().meridiem method. It receives hours as argument and returns meridiem text for that hour in current locale, so

 getMeridiemText(ampm: "am" | "pm") {
    return ampm === "am" ? this.moment().localeData().meridiem(0) : this.moment().localeData().meridiem(13);
  }

Will do the job

**Comment by dmtrKovalenko** [comment]
Cool! Would you like to make a PR so this works for all moment users of date-io?
