### ISSUE TITLE
Missing methods from "date-fns"

### ISSUE THREAD

**Issue by hazem3500** [dmtrKovalenko/date-io#479]
I was using "date-fns" and wanted to move to use "date-io" interface but I found a couple of methods that I am using are missing.
### Methods
- [`isDate`](https://date-fns.org/v2.16.1/docs/isDate)
- [`addYears`](https://date-fns.org/v2.16.1/docs/addYears) can be substituted with `addMonths(date, 12)`
- [`subMonths`](https://date-fns.org/v2.16.1/docs/subMonths) can be substituted with `addMonths(date, -1)`
- [`subYears`](https://date-fns.org/v2.16.1/docs/subYears) can be substituted with `addMonths(date, -12)`
- [`getWeek`](https://date-fns.org/v2.16.1/docs/getWeek)
- [`getQuarter`](https://date-fns.org/v2.16.1/docs/getQuarter)
- [`setQuarter`](https://date-fns.org/v2.16.1/docs/setQuarter)
- [`min`](https://date-fns.org/v2.16.1/docs/min)
- [`max`](https://date-fns.org/v2.16.1/docs/max)
- [`differenceInCalendarDays`](https://date-fns.org/v2.16.1/docs/differenceInCalendarDays)
- [`differenceInCalendarMonths`](https://date-fns.org/v2.16.1/docs/differenceInCalendarMonths)
- [`differenceInCalendarYears`](https://date-fns.org/v2.16.1/docs/differenceInCalendarYears)
- [`startOfQuarter`](https://date-fns.org/v2.16.1/docs/startOfQuarter)
- [`startOfYear`](https://date-fns.org/v2.16.1/docs/startOfYear)
- [`isSameQuarter`](https://date-fns.org/v2.16.1/docs/isSameQuarter)
- [`parseISO`](https://date-fns.org/v2.16.1/docs/parseISO)
- [`getTime`](https://date-fns.org/v2.16.1/docs/getTime)
- [`getDay`](https://date-fns.org/v2.16.1/docs/getDay)
- [`getDate`](https://date-fns.org/v2.16.1/docs/getDate)

I know that some of these methods can be achieved by using other methods in the current interface but am not sure how to handle the ones that aren't.
I am not sure if adding these methods to the interface is the best option since it will increase the API surface, what do you guys suggest for these kinds of situations?

**Comment by dmtrKovalenko** [comment]
Hey, thanks for raising this. My question – how you are planning to use date-io? If this really required I can add these methods – it's not a problem.

`sub*` methods will not be added in favor of negative number `addMonth(date, -12)`

**Comment by hazem3500** [comment]
@dmtrKovalenko I am forking [react-datepicker](https://github.com/Hacker0x01/react-datepicker) and trying to make it agnostic of the date-management library so it can support additional calendar systems.

I ended up creating the above functions using the available functions from `date-io`, it would be great if someone of them were added though.

**Comment by dmtrKovalenko** [comment]
Awesome! I will add all the required functions, but probably except the 
- `isDate` - makes no sense in cross-lib comparison
- `parseISO` – ISO strings perfectly parses using `new Date()` or `utils.date()`

**Comment by eps1lon** [comment]
> ISO strings perfectly parses using new Date()

That's debateable. `new Date(isoString)` just like `Date.parse` are "discouraged"<sup>1</sup> because of browser inconsistencies. Namely Safari assumes UTC when the timezone is missing in the ISO 8601 string while all other browsers assume local time.

`date-fns`' `parseISO` resolves these inconsistencies. `utils.date` should rather use `parseISO` under the hood if it's used with an ISO date. You can see that in https://cc8j3.csb.app the output of `parseISO` is consistent across chrome and safari while new Date output is different.

<sup>1</sup> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by dmtrKovalenko** [comment]
Yeah, that's weird. Thanks @eps1lon I will update the logic accrosss all the adapters

**Comment by bartvde** [comment]
has this been done? I don't see any reference to parseISO in the codebase

**Comment by dmtrKovalenko** [comment]
Parse iso can be done with native date. Then you can make date-io object from JS Date
