### ISSUE TITLE
add new Date format

### ISSUE THREAD

**Issue by hazem3500** [dmtrKovalenko/date-io#482]
I was looking for the format `YYYY/MM/DD` in the formats object but I didn't find any, isn't this a common format?
in Hijri it would be ``iYYYY/iMM/iDD``

**Comment by dmtrKovalenko** [comment]
Hmm, but we already have this – [keyboardDate](https://github.com/dmtrKovalenko/-date-io/blob/2c69cc1671ffff43897c8279279ca3841a301fd4/packages/core/IUtils.d.ts#L53)
