### ISSUE TITLE
npm ERR! 404 Not Found: @date-io/core@^1.3.6

### ISSUE THREAD

**Issue by janrider** [dmtrKovalenko/date-io#49]
Hi,

When I try to install **@date-io/date-fns** (`$ npm i @date-io/date-fns`) I got an error 
`npm ERR! 404 Not Found: @date-io/core@^1.3.6`. What am I doing wrong?

**Comment by dmtrKovalenko** [comment]
https://www.npmjs.com/package/@date-io/core
It is available

**Comment by janrider** [comment]
> https://www.npmjs.com/package/@date-io/core
> It is available

I see. But at the same time `$ npm i @date-io/core` returns `npm ERR! 404 Not Found: @date-io/core@latest` for me.

**Comment by dmtrKovalenko** [comment]
Hay, but it is working for me 😐

**Comment by dmtrKovalenko** [comment]
Dont you using some custom registry. Have you tried yarn?

**Comment by janrider** [comment]
I apologize for the concern. Problem was with .npmrc setup
