### ISSUE TITLE
There is no 'date-fns/getDayOfYear' function

### ISSUE THREAD

**Issue by AlekseyMalakhov** [dmtrKovalenko/date-io#517]
Please, add 'date-fns/getDayOfYear' function in your library. Thank you.
Best regards,
Aleksey

**Comment by dmtrKovalenko** [comment]
I've been thinking about this and I'd say that we will not implement it. 
It is not a rare use case when you need to use a day of the year in typical calendar implementation. 

If it's really needed you can extend the interfaces by your own
