### ISSUE TITLE
Wrong utc output when using the dayjs adapter with dayjs

### ISSUE THREAD

**Issue by mkarajohn** [dmtrKovalenko/date-io#518]
**Describe the bug**
Using `dayjs.utc().format()` after the `dayjs` has been extended as described [here](https://day.js.org/docs/en/plugin/utc) returns the output `"2020-12-26T21:08:04+00:00"`

**Expected behavior**
According to [the documentation](https://day.js.org/docs/en/plugin/utc) executing that code should return the string `"2020-12-26T21:08:04Z"`

**More Info**
Turns out this is an issue with the `@date-io/dayjs`. Just loading it by `import`ing it, causes this issue. Try it [here](https://codesandbox.io/s/naughty-hawking-jriuz?file=/src/App.js) with the import commented out and it works as expected (you need to refresh the "browser" view though in order to apply the changes).

Updating to version 2 does not fix the issue (in any case I cannot update to v2 since `@material-ui/pickers` [recommends](https://material-ui-pickers.dev/getting-started/installation#peer-library:~:text=Important%3A) v1 for use with their version 3)

**Setup**
- @date-io/dayjs Version: 1.3.13
 - Day.js Version: 1.9.7
 - OS: Linux
 - Browser: Chromium 87.0.4280.88
 - Time zone: +2

**Comment by dmtrKovalenko** [comment]
Unfortunately, we are not working on the v1 version. Please update the pickers (or move to the material-ui v5 alpha)
