### ISSUE TITLE
[1.13.3] Wrong `yearMonthFormat` format for date-fns utils

### ISSUE THREAD

**Issue by sanex3339** [dmtrKovalenko/date-io#544]
https://github.com/dmtrKovalenko/date-io/blob/v1.3.13/packages/date-fns/src/date-fns-utils.ts#L44

It should be `LLLL yyyy`.

If possible, please release a patch version with this fix.
Also I can create a PR with the fix

**Comment by dmtrKovalenko** [comment]
It was fixed long ago in v2. Sorry for long response

**Comment by dmtrKovalenko** [comment]
v1 u
