### ISSUE TITLE
Make internal format function always use this.format

### ISSUE THREAD

**Issue by dmtrKovalenko** [dmtrKovalenko/date-io#55]
In order to make it easy override format behavior with class inheritance. Like for date-fns-tz
```js
class DateFnsTzUtils {
  format(date, formatString) {
    return formatTz(date, formatString, {
      timeZone: "America/New_York",
      locale: this.locale
    });
  }
}
```

**Comment by zsid** [comment]
Another thing to consider is `disablePast` -> How would this be affected if we specify a time zone? Ideally, it should not show the dates that are in the past for that particular timezone.

**Comment by dmtrKovalenko** [comment]
yeah, then `isBefore` and `isAfter` should be overrided as well
