### ISSUE TITLE
Weird format output . v1.x version.

### ISSUE THREAD

**Issue by JanderSilv** [dmtrKovalenko/date-io#557]
Hello, first of all thanks for this lib.

I'm using the v1.x version because it was asked by material-ui-pickers' lib.

_Important: For material-ui-pickers v3 use v1.x version of @ date-io adapters._

And trying to replicate the docs example, i'm getting this output.

![image](https://user-images.githubusercontent.com/42092038/113307658-c412ed80-92db-11eb-814d-ae73ba247e62.png)
![image](https://user-images.githubusercontent.com/42092038/113307732-d725bd80-92db-11eb-81e1-ab8402e3e261.png)
![image](https://user-images.githubusercontent.com/42092038/113307780-e0af2580-92db-11eb-8984-edd62381e599.png)

**Comment by dmtrKovalenko** [comment]
It looks like you should use old luxon version :( 

Sorry, we are not supporting v1 so I did not respond to this issue, my bad
