### ISSUE TITLE
[1.3.13] Bugs with @date-io/luxon on ios safari

### ISSUE THREAD

**Issue by sharapov2701** [dmtrKovalenko/date-io#562]
The calendar does not display March, September is displayed 2 times, December is displayed as the first month of the year instead of January. Tested on iPhone 6 with safari v12.5.2. [Codesandbox ](https://codesandbox.io/s/material-ui-pickers-playground-forked-djp5o) to reproduce the bug.

**Comment by dmtrKovalenko** [comment]
v1 is not supported
