### ISSUE TITLE
Luxon module does not support starting the weekday based on Locale, only starts on Monday.

### ISSUE THREAD

**Issue by georgesglynn** [dmtrKovalenko/date-io#567]
From the documentation and code I have looked through, Luxon only supports making the week start on Monday. Instead of being able to change this based on locale or at the very least having a mechanism to make it start on Sunday for USA users.

![image](https://user-images.githubusercontent.com/16637813/116749655-de1d1a00-a9c6-11eb-978f-9bd337034f98.png)

This is a [material-ui-pickers](https://material-ui-pickers.dev/) date view.

**Comment by dmtrKovalenko** [comment]
Luxon based on intl, which is not giving a lot of configs. 

If you will find how to change this setting we can update the implementation
