### ISSUE TITLE
Add duration plugin from dayjs to @date-io

### ISSUE THREAD

**Issue by dkleber89** [dmtrKovalenko/date-io#568]
Is it possible to add the dayjs plugin "duration" to @date-io? Or is it possible to extend de dayjs inside the @date-io that i can use the duration within the @date-io lib in context of typescript?

**Comment by dmtrKovalenko** [comment]
What is the use case?

**Comment by dmtrKovalenko** [comment]
BTW You can pass your own instance of dayjs to the constructor

**Comment by dkleber89** [comment]
I see the possibility to pass my own instance to the constructor but then i have the problem with the typescript support. because in the date-io lib are `typeof defaultDayjs` are used. 

UseCase:
We build a component lib for many projects in our company. So we want to use date-io as abstraction for the usage of a dayjs/date-fns etc. lib .... So we want to achieve to only use date-io in our lib and never use the date / time lib directly

BTW i hope my english is understandable :-)

**Comment by dmtrKovalenko** [comment]
Yeah that is reasonable, we need to make proper type inference through generics
