### ISSUE TITLE
Support Luxon 2

### ISSUE THREAD

**Issue by dantman** [dmtrKovalenko/date-io#580]
Luxon has released a new major version Luxon 2 ([upgrade notes](https://moment.github.io/luxon/#/upgrading?id=_1x-to-20)).

It appears that nothing date-io uses has changed. So the only thing that needs to be done is updating the `peerDependencies` from `"luxon": "^1.21.3"` to `"luxon": "^1.21.3 || ^2"`.

**Comment by oliviertassinari** [comment]
@dantman I don't have admin right on this repository, but maybe you would like to open a PR?

**Comment by dantman** [comment]
Looks like date-io doesn't have tests. So all I could do in the pr is edit the package.json but I wouldn't be able to verify it actually works.
```diff
diff --git a/packages/luxon/package.json b/packages/luxon/package.json
index f767468..b479522 100644
--- a/packages/luxon/package.json
+++ b/packages/luxon/package.json
@@ -11,3 +11,3 @@
   "peerDependencies": {
-    "luxon": "^1.21.3"
+    "luxon": "^1.21.3 || ^2"
   },
@@ -22,4 +22,4 @@
   "devDependencies": {
-    "@types/luxon": "^1.21.0",
-    "luxon": "^1.21.3",
+    "@types/luxon": "^1.27.1",
+    "luxon": "^2.0.2",
     "rollup": "^2.0.2",
```

**Comment by dmtrKovalenko** [comment]
It has 100% coverage. Please open PR and I'll take a look :)

Thank you.
