### ISSUE TITLE
"fromNow / toRelative / formatDistance" Support

### ISSUE THREAD

**Issue by amerryma** [dmtrKovalenko/date-io#586]
Will there be planned support for the "4 days ago" type formatting for dates?

Most of the libraries do this, but their interfaces are different:

| Date Library | Method         |
|--------------|----------------|
| luxon        | toRelative     |
| date-fns     | formatDistance |
| moment       | fromNow        |

**Comment by dmtrKovalenko** [comment]
Unsure about this, it's not really easy because for dayjs it requires additional plug-in and for Luxon Intl Relative time is not supported in non-chrome edge for example. 

I think if you need this -- it's the perfect example where extension of interface will fit perfectly.

**Comment by dmtrKovalenko** [comment]
Closing this for now
