### ISSUE TITLE
Support for additional methods

### ISSUE THREAD

**Issue by benmccann** [dmtrKovalenko/date-io#6]
We've been discussing the need for just such a library over at Chart.js where our users are complaining about our usage of moment making the download size too large.

I scanned our code and it looks like we would need the following methods in order to use date-io:

```
luxon?: any
fromMillis(millis): TDate
fromJSDate(jsDate): TDate
TDuration.as(unit: string) or getDiff(TDate, TDate, unit: string)
TDate.startOf(unit: string)
TDate.endOf(unit: string)
```

**Comment by dmtrKovalenko** [comment]
I am glad to see that you interested in this project. I will add new methods for interface in the next release.  

BTW really like chart js 😎

**Comment by benmccann** [comment]
@dmtrKovalenko I think we're leaning towards trying to implement this without date-io at the moment (no pun intended), so I'll close this issue for now. I still really like what you're doing with this project and will keep it in mind for the future!
