### ISSUE TITLE
Cannot read properties of undefined (reading 'replace') with DayJS

### ISSUE THREAD

**Issue by yanickrochon** [dmtrKovalenko/date-io#602]
I am receiving the error `Cannot read properties of undefined (reading 'replace')`.

Upon investigating, I find that this line declares `fullDate` as `"ll"`

https://github.com/dmtrKovalenko/date-io/blob/e70582f726e4612ba08acb4083112803f790994f/packages/dayjs/src/dayjs-utils.ts#L47

Whereas DayJS declares no such format, but `"LL"` (see [here](https://github.com/iamkun/dayjs/blob/4a7b7d07c885bb9338514c234dbb708e24e9863e/src/plugin/localizedFormat/utils.js#L9))

This results in this line failing because there is no such format available

https://github.com/dmtrKovalenko/date-io/blob/e70582f726e4612ba08acb4083112803f790994f/packages/dayjs/src/dayjs-utils.ts#L177

Where the above line has these arguments :

* `date` a DayJS instance
* `formatString` the value `"ll"`

**Comment by dmtrKovalenko** [comment]
We have test suite that covers all the formats, and here is a fullDate working https://github.com/dmtrKovalenko/date-io/blob/c694d02d849d2d9f98f337b99abf7398a006856d/__tests__/formats.test.ts#L67

**Comment by yanickrochon** [comment]
The point is that this lib decalres an alias of `fullDate` to be `ll`, whereas DayJS defines no such format, but `LL`.

**Comment by dmtrKovalenko** [comment]
@yanickrochon it has this format with plugin we are including by default https://day.js.org/docs/en/display/format#localized-formats
