### ISSUE TITLE
not working with @material-ui/pickers

### ISSUE THREAD

**Issue by Azrideus** [dmtrKovalenko/date-io#618]
Im getting `utils.getYearText is not a function` error when working with `@material-ui/pickers` and `@date-io/date-fns-jalali`'s DateUtils

```
import JalaliUtils from "@date-io/date-fns-jalali";
...
<MuiPickersUtilsProvider utils={JalaliUtils} locale={localeDates}>
```

before this, I was using `@date-io/date-fns` and got the same error so I had to downgrade my version to 1.3.13 and it worked
but downgrading `@date-io/date-fns-jalali` does not seem to fix the issue

**Comment by dmtrKovalenko** [comment]
Thats because date-fns-jalaali was created later than @material-ui/pickers was archived. 
You should upgrade to core @mui/pickers
