### ISSUE TITLE
Refactor arrow-methods from LuxonUtils 

### ISSUE THREAD

**Issue by local-minimum** [dmtrKovalenko/date-io#619]
Since arrow-methods are not available when sub-classing the `LuxonUtils` (e.g. to have it always use UTC rather than local-time) through `super` it would be better if the implementation of `IUtils<DateTime>` was doing something like:

```ts
export default class LuxonUtils implements IUtils<DateTime> {
  public date(value?: any): DateTime | null {
     /* ... */
  };
```

instead of

```ts
export default class LuxonUtils implements IUtils<DateTime> {
  public date = (value?: any) => {
     /* ... */
  };
```

because then subclassing could be done like so (which is not possible when `date` is defined with `=>` as it is now:

```ts
export class LuxonUTCUtils extends LuxonUtils {
  public override date(value?: any): DateTime | null {
    const dt = super.date(value);
    if (dt === null) return null;
    return dt.toUTC();
  };
}
```

**Comment by Semigradsky** [comment]
See https://github.com/dmtrKovalenko/date-io/issues/595 also

**Comment by dmtrKovalenko** [comment]
That was a mistake done by me by converting all of them from the regular js method to class properties, which causes breaking change, so switching back would be another breaking change. 

For now please follow this guide https://github.com/dmtrKovalenko/date-io#2-reexport-the-bindings
