### ISSUE TITLE
Why typescript is in deps, not dev deps?

### ISSUE THREAD

**Issue by gentlee** [dmtrKovalenko/date-io#641]
It should be in dev deps.

**Comment by gentlee** [comment]
Same as @types/jest

**Comment by dmtrKovalenko** [comment]
It is not, the root package.json is just a workspace. The real dependcies are the only @date-io/core
<img width="419" alt="image" src="https://github.com/dmtrKovalenko/date-io/assets/16926049/a5daff2b-1b4a-465b-840d-5b979107fc98">
