### ISSUE TITLE
Support for date-fns 3

### ISSUE THREAD

**Issue by NathanAP** [dmtrKovalenko/date-io#655]
Hi!

I'm working on a project using Vite, Vue and Vuetify (I guess its not really relevant for the issue, I just found the problem by them). This morning I tried to update date-fns to version 3, but I cannot run my project anymore.

I'm getting this when I try to open the project on my browser:

![image](https://github.com/dmtrKovalenko/date-io/assets/12821171/6b3b60c6-2153-429d-8072-a8749f615603)

Reverting date-fns from `3.0.6` to `2.30.0` fixes the problem and my project can run again. Is there something we can do to fix it?

edit: updated image to show just the relevant part.

**Comment by kossnocorp** [comment]
@dmtrKovalenko I just shipped https://github.com/date-fns/date-fns/releases/tag/v3.2.0 that exports `longFormatter` and other internals from `format`: https://github.com/date-fns/date-fns/commit/3d85c7df7f25267e4774103addd773d99b455edb

It should help v3 adapter

**Comment by dmtrKovalenko** [comment]
That's wonderful @kossnocorp thanks for doing this. The support of date-fns v3 was shipped in @date-io/date-fns v3 just now 🥳

**Comment by kossnocorp** [comment]
@dmtrKovalenko you're welcome
