### ISSUE TITLE
Inconsistency in getMonth and setMonth Methods

### ISSUE THREAD

**Issue by SoheilHasankhani** [dmtrKovalenko/date-io#660]
The `getMonth` method is currently working with the Jalali month, while the `setMonth` method operates with the Gregorian month. This inconsistency leads to a failure in the following simple test:
```javascript
it("Jalaali -- setAndGetMonth", () => {
    const date = jalaaliUtils.date(TEST_TIMESTAMP);
    const newDate = jalaaliUtils.setMonth(date, 0);
    expect(jalaaliUtils.getMonth(newDate)).toBe(0);
});
```
The `getDate` method has been overridden to work with `jDate`:

```js
public getMonth = (date: Moment) => {
    return date.jMonth();
};
```

However, the `setDate` method has not been adjusted to match this behavior. This inconsistency needs to be addressed to ensure the correct functioning of the library.

**Comment by dmtrKovalenko** [comment]
Does it only affect moment jalaali? Could you please submit a PR with a test to fix this behavior as you already did?
