### ISSUE TITLE
dependencies should be devDependencies?

### ISSUE THREAD

**Issue by benmccann** [dmtrKovalenko/date-io#7]
There are a number of `dependencies` declared:
https://github.com/dmtrKovalenko/date-io/blob/master/package.json#L23

These look like they should all be `devDependencies` as they look like things that would only be used at development time

**Comment by TrySound** [comment]
@benmccann It's private package. Published packages are placed here
https://github.com/dmtrKovalenko/date-io/tree/master/packages

@dmtrKovalenko Could you mark root package.json as private?

**Comment by benmccann** [comment]
Ah, I see. Thank you

**Comment by benmccann** [comment]
I've sent a PR for that here: https://github.com/dmtrKovalenko/date-io/pull/9
