### ISSUE TITLE
Is babel & webpack required?

### ISSUE THREAD

**Issue by benmccann** [dmtrKovalenko/date-io#8]
I see that material-ui-pickers does the following:

```
import { IUtils } from '@date-io/core/IUtils';
```

I had never seen `@` before. It looks to me like [something that works only with babel & webpack since it's not part of the ecmascript spec](https://stackoverflow.com/questions/42711175/what-does-the-symbol-do-in-javascript-imports)?

It might be useful to document the ways of including date-io in a project

**Comment by TrySound** [comment]
@benmccann It's scoped package. It's part of node resolver. Nothing special. And yes, esm bundle is built for bundlers, cjs bundle is built for node.

**Comment by dmtrKovalenko** [comment]
@benmccann the @ symbol is just npm feature for scoped packages (more info [here](https://docs.npmjs.com/misc/scope)). Actually Material-ui-pickers imports only typescript interface ‘cause they are written in typescript themself. 

Including of date io is very simmilar to date fns. Each package here is an object implemented the same interface. User must pass you that object one time. And then you will use it for date management

**Comment by benmccann** [comment]
Oh, that's a bit different than I imagined this worked. It would be really helpful to show the user passing the object in the readme
