### ISSUE TITLE
Mix up of standalone and format tokens for date-fns

### ISSUE THREAD

**Issue by ronaldruzicka** [dmtrKovalenko/date-io#97]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    ^3.2.0     |
| material-ui          |    ^4.2.0     |
| React                |     ^16.8.6    |
| date-fns        |    2.0.0-beta.2     |

## Steps to reproduce

1. Basic setup for `date-fns`
2. Open Datepicker and choose date, e.g. July 24, 2019

## Expected behavior
The translation in the Datepicker header should be in nominative: **červenec**

## Actual behavior
The translation in the Datepicker header is in genitive: **července**

![Screen Shot 2019-07-24 at 09 05 39](https://user-images.githubusercontent.com/20684387/61792043-166bed80-ae1c-11e9-9eb5-6bfadbf9cd89.png)

## Live example
https://codesandbox.io/s/material-ui-pickers-usage-demo-29nmv

I found out that `getCalendarHeaderText` is always called with `MMMM yyyy` which is formatted and it should be instead standalone `LLLL yyyy` shouldn't it? 

```js
// date-fns/src/date-fns-utils.ts
// this.yearMonthFormat = "MMMM yyyy";

DateFnsUtils.prototype.getCalendarHeaderText = function (date) {
  return format(date, this.yearMonthFormat, { locale: this.locale });
};
```

Other formats could be fixed as well. I switched the order of month and day to match my language (Czech or Slovak), not sure if it is applicable for other languages as well 🤔🤷🏻‍♂️

| format                         | Bad                                      | Good   |
| ---------------------| -------------------------- |------- |
| yearMonthFormat     |     MMMM yyyy                    | LLLL yyyy |
| dateTime12hFormat  |     MMMM do hh:mm aaaa | do MMMM hh:mm aaaa |
| dateTime24hFormat |     MMMM do HH:mm         | do MMMM HH:mm |
| dateFormat                |     MMMM do                       | do MMMM |

**Comment by dmtrKovalenko** [comment]
Yeah, I thought about our formats are not really the best. But any change here will be a breaking change right, so cannot deliver it right now.
I planned new breaking change closer to the end of August 

Right now you can override formats with a help of utils

**Comment by ronaldruzicka** [comment]
Thanks, but how can I overwrite it? 
I tried this, but it didn't override the defaults
```js
const DateFnsUtilsCustom = new DateFnsUtils({ yearMonthFormat: 'LLLL yyyy' })

<MuiPickersUtilsProvider locale={cs} utils={DateFnsUtilsCustom}>...</MuiPickersUtilsProvider>
```
